POOP_TRIVIA = [
    "The average person poops about 1–2 times per day, but anywhere from 3 times a week to 3 times a day is still considered normal.",
    "A healthy poop is typically 75% water and 25% solid matter.",
    "The Bristol Stool Chart is a medical tool that categorizes poop into seven types to evaluate digestive health.",
    "Gut bacteria are responsible for most of the smell of poop—over 50% of poop's solid mass is actually bacteria.",
    "Koalas have cube-shaped poop, which helps the pellets stack and mark territory.",
    "Corn kernels often appear in poop because the outer shell contains cellulose, which humans cannot fully digest.",
    "Poop gets its brown color from a pigment called stercobilin, produced when red blood cells break down.",
    "Human poop can be used to produce biogas, which can generate electricity or fuel.",
    "Dogs sometimes eat poop (coprophagia) due to nutrient deficiencies, instinct, or curiosity.",
    "The phrase 'Number Two' became popular in the U.S. in the 20th century as a polite euphemism for defecation.",
    "Sloths only poop about once a week and can lose up to one-third of their body weight in a single poop.",
    "Wombats produce cube-shaped poop because their intestines shape it through varying elasticity.",
    "An elephant can poop up to 150 kilograms (330 pounds) per day.",
    "Blue whales release massive ‘poop plumes’ that are bright orange and help fertilize the ocean.",
    "A healthy poop sinks slowly, while a very floaty poop often indicates excess gas.",
    "Termites produce methane-rich poop that contributes to global methane emissions.",
    "Scientists can determine an animal’s diet and health by analyzing its poop DNA.",
    "Caterpillars shoot their poop (called frass) several feet away to avoid predators finding them.",
    "Hippos spray poop by spinning their tails like propellers to mark territory.",
    "A buildup of undigested plant matter makes panda poop extremely fibrous.",
    "Astronauts’ waste used to be jettisoned into space, where it sometimes froze into tiny poop-ice comets.",
    "Bat guano is so nitrogen-rich it’s used as a powerful natural fertilizer.",
    "The average bowel movement travels through the colon at about 2 inches per hour.",
    "Some fish, like parrotfish, poop sand after grinding coral in their digestive systems.",
    "Healthy human poop should be shaped like a soft sausage according to the Bristol Stool Chart.",
    "Sharks sometimes follow trails of fish poop because it signals prey nearby.",
    "Rabbits eat some of their own poop (cecotropes) to maximize nutrient absorption.",
    "Human feces contain traces of gold, though not enough to mine economically.",
    "The color of poop can change due to food dyes, like red from beets or green from spinach.",
    "Cow dung is used as building material in parts of the world due to its insulating properties.",
    "Some ants farm aphids and drink their honeydew, which is basically aphid poop.",
    "People can detect health issues like bleeding or infection by observing poop smell changes.",
    "Flies are attracted to poop because it provides both food and a place to lay eggs.",
    "Hippo poop helps fertilize African rivers, supporting fish populations.",
    "The sound of a toilet flush doesn’t indicate how ‘complete’ a poop was—just water turbulence.",
    "Bird poop is white because birds excrete uric acid instead of urine.",
    "The average poop is 6 to 12 inches long.",
    "Camel poop is so dry it can be burned immediately as fuel.",
    "Some lizards shoot out foul-smelling poop as a defense mechanism.",
    "Healthy poop should not stick excessively to the toilet bowl.",
    "Females in many species inspect male poop piles to judge diet quality.",
    "Goose poop can contain traces of undigested seeds that grow into plants.",
    "Early Chinese gunpowder production used bat and bird guano.",
    "Horses produce around 50 pounds of poop per day.",
    "Dog poop can reveal whether a dog is stressed or anxious based on consistency.",
    "1960s submarines compacted crew poop into weighted containers and dumped them at sea.",
    "Poop transplants (fecal microbiota transplants) can restore healthy bacteria in the gut.",
    "Koala poop smells like the eucalyptus leaves they eat.",
    "Some turtles breathe through their butts, and their waste output reflects this adaptation.",
    "Baby poop is usually odorless until bacteria colonize the gut.",
    "A person may pass gas up to 20 times a day as part of normal digestion.",
    "Crocodile poop often contains bone fragments from their meals.",
    "Termite mounds are partly constructed from hardened termite poop.",
    "Some beetles roll dung balls many times their own weight.",
    "Human poop contains around 100 billion bacteria per gram.",
    "A change in stool shape can indicate colon issues like polyps or narrowing.",
    "The world’s oldest fossilized poop (coprolite) is over 500 million years old.",
    "Hyenas use communal poop pits to communicate territory boundaries.",
    "Moose poop pellets are used by some artisans to make novelty jewelry.",
    "Some plants rely on bird poop to spread their seeds long distances.",
    "Doctors sometimes ask about poop color to detect liver and gallbladder issues.",
    "Feces sink or float depending on gas content and fat levels.",
    "A gorilla’s massive plant-based diet makes its poop highly fibrous.",
    "Snakes digest food slowly; they may poop only a few times per month.",
    "Camels conserve water so efficiently that their poop is almost completely dry.",
    "Penguins’ projectile pooping can reach up to 4 feet due to digestive pressure.",
    "Human poop smell comes mostly from sulfur-containing compounds.",
    "Scientists study dinosaur coprolites to learn about extinct diets.",
    "A sudden shift to vegetarian diet can make poop volume increase noticeably.",
    "Cats bury their poop instinctively to hide scent from predators.",
    "Goat poop forms small dry pellets because goats extract so much water from food.",
    "Fecal matter from cows produces methane used in renewable energy production.",
    "Poop quality can be affected by stress as much as by diet.",
    "Ancient Romans used fermented urine (not poop) for cleaning clothes due to ammonia.",
    "Whale poop floats, making it easier for scientists to collect samples.",
    "Diarrhea evolved as a defense to flush pathogens from the gut quickly.",
    "The gut microbiome influences poop smell more than the food itself.",
    "Healthy poop should not require painful straining to pass.",
    "Insects like cockroaches leave behind tiny poop specks that can trigger allergies.",
    "The word 'scatology' refers to the study of feces.",
    "Crabs often leave poop trails when walking underwater.",
    "Fruit bats’ poop helps spread fruit seeds widely across forests.",
    "The average adult produces about 150 grams of feces per day.",
    "Overuse of antibiotics can alter poop to become looser or paler.",
    "Human poop can reveal markers of diseases like Crohn's or celiac disease.",
    "Lion poop has strong ammonia odor due to a meat-heavy diet.",
    "Octopus poop resembles thin strings due to fluid diet.",
    "Healthy poop shouldn’t feel oily or leave greasy residue in water.",
    "Squirrels sometimes forget where they poop, leading to seed germination.",
    "Owl pellets are not poop—they’re regurgitated material—but often mistaken for feces.",
    "Poop can tell researchers about pollution levels when collected from aquatic animals.",
    "A pale clay-colored stool can indicate blocked bile ducts.",
    "Some monkeys throw poop as a form of defense or communication.",
    "Sheep poop pellets help fertilize grazing fields naturally.",
    "Hedgehog poop is long and dark with insect parts often visible.",
    "The smell of poop changes depending on fermentation in the gut.",
    "Bacteria in poop help regulate serotonin levels in the body.",
    "Good hydration helps poop retain a soft, smooth texture.",
    "Some birds poop on their legs to cool themselves via evaporation.",
    "Frog poop is surprisingly large compared to their body size.",
    "Pigs do not sweat, but their poop remains moist due to water-rich diet.",
    "Buffalo poop is traditionally used in some cultures as fuel and flooring.",
    "Certain butterflies drink animal poop to obtain minerals.",
    "Reptiles produce a white pasty substance with poop—this is concentrated uric acid.",
    "Old fossilized poop can contain pollen that shows ancient climate conditions.",
    "Sea cucumbers expel parts of their internal organs with poop during stress.",
    "A sudden increase in poop frequency can be caused by high-fiber diets.",
    "Dung beetles navigate using the Milky Way while rolling poop balls."
]
