name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies into package folder
      # - name: Install dependencies for Lambda
      #   run: |
      #     python -m pip install --upgrade pip
      #     mkdir -p package
      #     pip install -U git+https://github.com/thoellrich/july.git@fix-mpl.cbook.MatplotlibDepreciationWarning -t package

      # Run tests before deployment
      - name: Run tests
        run: |
          python -m pip install pytest
          python -m pytest tests/

      # 4. Copy project files into package folder
      - name: Copy project files
        run: |
          mkdir -p package
          cp *.py package/

      # 5. Create deployment ZIP
      - name: Zip deployment package
        run: |
          cd package
          zip -r ../lambda_deploy.zip .
          cd ..

      # 6. Configure AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::163368111864:role/role-githubdeploy-whenpoopbot
          aws-region: ap-southeast-1

      # 7. Deploy to AWS Lambda
      - name: Deploy to Lambda
        run : |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda_deploy.zip


docker run --rm -v "$PWD":/var/task public.ecr.aws/lambda/python:3.11 \
  /bin/bash -c "
    pip install -U git+https://github.com/thoellrich/july.git@fix-mpl.cbook.MatplotlibDepreciationWarning -t python &&
    zip -r july_layer.zip python
  "

docker run --rm -v "$PWD":/var/task july-build \
  /bin/bash -c "
    pip install -U git+https://github.com/thoellrich/july.git@fix-mpl.cbook.MatplotlibDepreciationWarning -t python &&
    zip -r july_layer.zip python
  "